-- AlterTable
ALTER TABLE `customer` ADD COLUMN `knustEmail` VARCHAR(191) NULL,
    ADD COLUMN `studentIdRef` VARCHAR(191) NULL,
    ADD COLUMN `studentVerificationMethod` ENUM('EMAIL', 'STUDENT_ID', 'EITHER') NULL,
    MODIFY `userType` ENUM('KNUST_STUDENT', 'STUDENT', 'RESEARCHER', 'CREATOR', 'STARTUP', 'BUSINESS', 'NGO', 'CORPORATE', 'OTHER') NOT NULL DEFAULT 'OTHER';

-- AlterTable
ALTER TABLE `package` ADD COLUMN `studentOnly` BOOLEAN NOT NULL DEFAULT false,
    MODIFY `category` ENUM('STUDIO_RENTAL', 'MEMBERSHIP', 'PRODUCTION', 'CORPORATE', 'STUDENT', 'OTHER') NOT NULL DEFAULT 'STUDIO_RENTAL';
